platform :ios, '8.0'
target “TestRAC” do


#字典转模型
pod 'MJExtension', '~> 3.0.13'
#表格刷新控件
pod 'MJRefresh', '~> 3.1.12'
#
pod 'MJReachability', '~> 1.0.0'
#图片加载
pod 'SDWebImage', '~> 3.8.1'
#数据库
pod 'LKDBHelper', '~> 2.3.2'
#网络请求工具
pod 'AFNetworking', '~> 3.1.0'

pod 'Masonry'

pod 'ReactiveCocoa'
pod 'ReactiveViewModel', tag: '0.1.2', git: 'https://github.com/ashfurrow/ReactiveViewModel.git'

end